spring.application.name=LocadoraGames

# Configurações do banco de dados

# Habilita o console do H2 no navegador
spring.h2.console.enabled=true
# Define o caminho para acessar o console (ex: localhost:8080/h2-console)
spring.h2.console.path=/h2-console

# Configuração da URL de conexão
spring.datasource.url=jdbc:h2:mem:locadoradb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostra as queries SQL no console
spring.jpa.show-sql=true